---
fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    inifile:
      repo: "https://github.com/puppetlabs/puppetlabs-inifile"
  symlinks:
    opendmarc: "#{source_dir}"

